name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.1
        options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint Dockerfile
      run: |
        docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.1
        options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: qalita/terra-argo-runner:latest
